[project]
name = "docker-custom-image"
version = "0.1.0"
description = "Trying out different things with AutoGen Framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
]
